name: maestro-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  maestro-run:
    runs-on: ubuntu-latest

    steps:
      - name: Carga el codigo
        uses: actions/checkout@v4

      - name: Prepara setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  
          java-version: '17'     

      - name: Instalar Maestro CLI
        run: curl -fsSL "https://get.maestro.mobile.dev" | bash

      - name: Enable KVM group permissions
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0660", OPTIONS+="static_node=kvm"' | sudo tee /lib/udev/rules.d/99-kvm.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          ls -l /dev/kvm

      - name: Correr emulador de android + Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          script: |
            export PATH=$PATH:$HOME/.maestro/bin
            adb install apps/ECommerce.apk
            maestro test test/