name: maestro-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  maestro-run:
    runs-on: ubuntu-latest

    steps:
      - name: Carga el codigo
        uses: actions/checkout@v4

      - name: Prepara setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  
          java-version: '17'     

      - name: Instalar Maestro CLI
        run: |
          curl -fsSL "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> "$GITHUB_PATH"
      
      - name: Enable KVM group permissions
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0660"' | sudo tee /etc/udev/rules.d/99-kvm.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          sudo apt-get update && sudo apt-get install -y acl
          sudo setfacl -m u:"$USER":rwx /dev/kvm
          ls -l /dev/kvm

      - name: Correr emulador de android + Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          disable-linux-hw-accel: false
          disable-animations: true
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
          script: |
            export PATH=$PATH:$HOME/.maestro/bin
            adb wait-for-device
            adb install apps/ECommerce.apk
            maestro test test/
            maestro test --format junit --output junit-report.xml test/

      - name: Generar reporte HTML
        if: always()
        run: |
          npx --yes junit-viewer --results junit-report.xml --output maestro-report.html
          ls -la maestro-report.html

      - name: Subir reporte HTML (Artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maestro-html-report
          path: maestro-report.html